export const ROUTE_PATHS = {
  PARTNER_PROPERTIES: "/api/partner/properties",
  CHAT: "/api/chat",
  AUTH_LOGIN: "/auth/login",
  AUTH_CALLBACK: "/auth/callback",
  AUTH_REFRESH: "/auth/refresh",
  AUTH_LOGOUT: "/auth/logout",
  AUTH_ME: "/auth/me",
  TEST_AGENT_REPLY: "/api/test/agent-reply",
  TEST_COLUMN: "/api/test/column",
  WHATSAPP_WEBHOOK: "/api/webhook/whatsapp",
  WHATSAPP_TEMPLATES: "/api/whatsapp/templates",
  WHATSAPP_CAMPAIGNS: "/api/whatsapp/campaigns",
  WHATSAPP_PERFORMANCE: "/api/whatsapp/performance",
  WHATSAPP_FEEDBACK: "/api/whatsapp/feedback",
  HEALTH_LIVE: "/health/live",
  HEALTH_READY: "/health/ready"
} as const;

export const TABLE_NAMES = {
  PARTNERS: "partners",
  PROPERTIES: "properties",
  PROPERTY_BANKS: "propertyBanks",
  BANKS: "banks",
  BANK_PRODUCTS: "bankProducts",
  ADMIN_PENDING_ACTIONS: "adminPendingActions",
  DEVELOPER_ACTIONS: "developerActions",
  DEVELOPER_PROPERTY_LINKS: "developerPropertyLinks",
  ENTITY_MEDIA: "entityMedia",
  USER_PROFILES: "userProfiles",
  ORDERS: "orders",
  CONVERSATION_REASONS: "conversationReasons",
  THREAD_METADATA: "threadMetadata",
  CHAT_MESSAGES: "chatMessages",
  AGENT_SOULS: "agent_souls",
  USER_ACTIVITY: "userActivity",
  SEARCH_LOGS: "searchLogs",
  GLOBAL_SEARCH_CACHE: "globalSearchCache",
  PROPERTY_DETAIL_CACHE: "propertyDetailCache",
  USER_PROPERTY_EXPOSURE: "userPropertyExposure",
  KNOWLEDGE_RESEARCH: "knowledgeResearch",
  NOTIFICATIONS: "notifications",
  REVIEWS: "reviews",
  FAVORITES: "favorites",
  PROMPTS: "prompts",
  AI_SETTINGS: "aiSettings",
  KNOWLEDGE_PAGES: "knowledgePages",
  HUMAN_HANDOFFS: "humanHandoffs",
  PENDING_VERIFICATIONS: "pendingVerifications",
  OTP_REQUESTS: "otpRequests",
  VERIFIED_PHONES: "verifiedPhones",
  SESSION_TOKENS: "sessionTokens",
  ADMIN_USERS: "adminUsers",
  ADMIN_PROFILES: "adminProfiles",
  USER_ROLES: "userRoles",
  AGENT_TRACES: "agentTraces",
  WHATSAPP_INBOUND_EVENTS: "whatsappInboundEvents",
  WHATSAPP_DELIVERY_LOGS: "whatsappDeliveryLogs",
  WHATSAPP_VOICE_CONFIRMATIONS: "whatsappVoiceConfirmations",
  WA_TEMPLATES: "wa_templates",
  WA_TEMPLATE_VERSIONS: "wa_template_versions",
  WA_CAMPAIGNS: "wa_campaigns",
  WA_CAMPAIGN_RECIPIENTS: "wa_campaign_recipients",
  WA_SEND_JOBS: "wa_send_jobs",
  WA_SEND_ATTEMPTS: "wa_send_attempts",
  WA_CONVERSATION_WINDOWS: "wa_conversation_windows",
  WA_FEEDBACK_EVENTS: "wa_feedback_events",
  WA_NUMBER_PERFORMANCE_SNAPSHOTS: "wa_number_performance_snapshots",
  WA_POLICY_AUDIT_LOG: "wa_policy_audit_log",
  API_EVENT_LOG: "api_event_log",
  WEBHOOK_EVENT_LOG: "webhook_event_log",
  ADMIN_ACTION_AUDIT: "admin_action_audit",
  AGENT_MEMORY: "agentMemory",
  AGENT_MEMORY_EMBEDDINGS: "agentMemoryEmbeddings",
  ENTITY_RELATIONS: "entityRelations",
  AI_TOKEN_USAGE: "aiTokenUsage",
  SEARCH_ANALYTICS: "searchAnalytics",
  IDEMPOTENCY_JOURNAL: "idempotency_journal",
  OUTBOX_EVENTS: "outbox_events",
  DEAD_LETTERS: "dead_letters",
  SCHEDULER_JOBS: "scheduler_jobs",
  AGENT_LIFECYCLE_EVENTS: "agent_lifecycle_events",
  WORKFLOW_STEP_EVENTS: "workflow_step_events",
  CIRCUIT_BREAKER_STATE: "circuit_breaker_state",
  FEATURE_FLAGS: "feature_flags"
} as const;

export const CHANNELS = ["web", "app", "whatsapp"] as const;
export const PRIORITY_LEVELS = ["HIGH", "NORMAL", "LOW"] as const;

export const AGENT_STATES = [
  "IDLE",
  "RUNNING",
  "WAITING",
  "SLEEPING",
  "FAILED",
  "TERMINATED"
] as const;

export const WORKFLOW_STEP_STATES = [
  "PENDING",
  "RUNNING",
  "SUCCEEDED",
  "FAILED",
  "COMPENSATED",
  "CANCELLED"
] as const;
